INSERT INTO conceitos (conceito, macro_categoria, categoria, subcategoria, modulo_curso, prerequisito, conhecimento_atual, objetivo, data_estudo, tempo_investido_hrs, fonte_estudo, regras_operacionais, probabilidade, mercado_aplicavel, notas)
VALUES
('HTF - Contexto Geral','Operando por Tempo','HTF','Função','43-46','Análise Multi-TF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Define viés direcional principal | S/R mais importantes'),
('HTF - Tendência Maior','Operando por Tempo','HTF','Função','43-46','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Define Always In principal'),
('HTF - Define Viés','Operando por Tempo','HTF','Aplicação','43-46','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alta HTF = prefira compras no CTF | Baixa HTF = prefira vendas'),
('HTF - Canal ou TR Maior','Operando por Tempo','HTF','Leitura','43-46','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Canal no HTF = tendência no CTF'),
('HTF - BO em HTF','Operando por Tempo','HTF','Evento','43-46','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BO no HTF = oportunidade rara e grande'),
('HTF - Gráficos Mensais','Operando por Tempo','HTF','Aplicação','43-46','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gráficos mensais = stops mensais - perspectiva longa'),
('CTF - Execução Principal','Operando por Tempo','CTF','Função','43-46','Análise Multi-TF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Onde opera - gráfico 5 minutos padrão Al Brooks'),
('CTF - Padrões e Sinais','Operando por Tempo','CTF','Função','43-46','CTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identifica padrões e barra de sinal para entrada'),
('CTF - Gestão do Trade','Operando por Tempo','CTF','Função','43-46','CTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Onde gerencia stop e realiza'),
('LTF - Entrada Prematura','Operando por Tempo','LTF','Técnica','43-46','Análise Multi-TF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrar no LTF antes do sinal aparecer no CTF'),
('LTF - Confirmação de Força','Operando por Tempo','LTF','Técnica','43-46','LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Verificar força do movimento antes de entrar'),
('LTF - Melhor Preço','Operando por Tempo','LTF','Benefício','43-46','LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrar em price melhor ao usar LTF'),
('LTF - Gráfico 2 Minutos','Operando por Tempo','LTF','Aplicação','43-46','LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','TF inferior padrão para scalpers'),
('LTF - Gráfico 15 Segundos','Operando por Tempo','LTF','Aplicação','43-46','LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Ultra-LTF para scalp extremo - avançado'),
('Day Trade com Gráfico Diário','Operando por Tempo','Day Trade Diário','Framework','43-46','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Modo BTC/STC no diário | Micro canal | Aposta contra grandes barras'),
('BTC/STC no Gráfico Diário','Operando por Tempo','Day Trade Diário','Técnica','43-46','BTC e STC',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra/venda fechamento no gráfico diário'),
('Apostando Contra Grandes Barras de TR Diário','Operando por Tempo','Day Trade Diário','Técnica','43-46','TR e Barras Grandes',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Grandes barras de TR no diário = fade'),
('Perdendo por Erros Evitáveis','Gestão de Perdas','Erros','Identificação','47-50','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Psicologia / Crenças falsas / Gerenciamento ruim / Stop incorreto'),
('Crenças Falsas sobre Trading','Gestão de Perdas','Erros','Psicologia','47-50','Falsas Crenças',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identificar e eliminar crenças que causam perdas'),
('Gerenciamento Ruim de Risco','Gestão de Perdas','Erros','Técnico','47-50','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Stop incorreto / Tamanho errado / Sem plano'),
('Regras para Evitar Grandes Perdas','Gestão de Perdas','Erros','Prevenção','47-50','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Stop sempre presente / Tamanho correto / Plano pré-trade'),
('Stop Incorreto = Perda Maior','Gestão de Perdas','Erros','Consequência','47-50','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Stop arbitrário ou muito largo = catástrofe'),
('Fracionamento Cria Grandes Perdas','Gestão de Perdas','Erros','Consequência','47-50','Scale In em Perdedora',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Scale in em perdedora amplifica perda'),
('Boa Operação que Vai Mal','Gestão de Perdas','Perspectiva','Mentalidade','47-50','Aceitar Incerteza',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mesmo melhor setup pode perder - é probabilidade'),
('Precisa de Regras para Boa Operação Mal','Gestão de Perdas','Perspectiva','Regras','47-50','Boa Operação',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Stop técnico protege quando setup falha'),
('Todas Tendências Desapontam','Gestão de Perdas','Perspectiva','Realidade','47-50','Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Nenhuma tendência é perfeita - aceitar drawdowns'),
('Se Premissa Mudar - Mude Estilo','Gestão de Perdas','Perspectiva','Adaptação','47-50','Premissa Mudou',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Contexto mudou = estratégia muda'),
('Traders Emboscados','Gestão de Perdas','Perspectiva','Psicologia','47-50','Trapped Traders',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Emboscados na direção errada - saiam rápido'),
('Evitar Operações Ruins','Gestão de Perdas','Prevenção','Seleção','47-50','Checklist Pré-Trade',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pule setups ruins - seja seletivo'),
('Identificar Always In Direction','Habilidades Práticas','Leitura Contexto','Habilidade Core','12-18','Conceito Always In',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Determinar AIL ou AIS em tempo real - tarefa 1'),
('Identificar Fase do Mercado','Habilidades Práticas','Leitura Contexto','Habilidade Core','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tendência/Canal/TR/BO em tempo real'),
('Reconhecer Tendência de Alta','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Tendência Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Série de HLs clara - compradores controlam'),
('Reconhecer Tendência de Baixa','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Tendência Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Série de LHs clara - vendedores controlam'),
('Identificar Trading Range','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Reconhecer lateralidade vs tendência'),
('Identificar Canal','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Traçar linhas paralelas corretamente'),
('Avaliar Qualidade da Tendência','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Qualidade Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Forte vs Fraca - impacta estratégia'),
('Identificar Tipo de Canal','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Tipos Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Estreito/Amplo/Micro - diferentes estratégias'),
('Reconhecer Micro Canal','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Micro Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identificar tendência mais forte / clímax'),
('Identificar TTR','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','TTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tight trading range - compressão'),
('Determinar Posição em TR','Habilidades Práticas','Leitura Estrutura','Habilidade','12-18','Posição TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Topo/Meio/Fundo/Metades - define estratégia'),
('Ler Barras de Sinal','Habilidades Práticas','Leitura Barras','Habilidade Core','08-11','Barra de Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Qualidade: forte/fraca/ruim - base da execução'),
('Avaliar Qualidade do Sinal','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Qualidade Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Corpo/fechamento/sombra - decisão de entrar'),
('Reconhecer Inside Bars (i e ii)','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Inside Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identificar compressão'),
('Reconhecer Outside Bars (o e oo)','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Outside Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identificar volatilidade'),
('Identificar Dojis','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Doji',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Indecisão - ajustar estratégia'),
('Reconhecer Barras de Tendência','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Barra Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alinhadas com direção - força'),
('Identificar Barras de Surpresa','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Barra Surpresa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Movimento inesperado forte'),
('Identificar Barras de Desistência','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Barra Desistência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Exaustão - reversão minoritária'),
('Marcar Swing Highs e Lows','Habilidades Práticas','Leitura Estrutura','Habilidade','19-29','Swing High/Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pivots importantes - automático'),
('Identificar S/R Relevantes','Habilidades Práticas','Leitura Estrutura','Habilidade','19-29','Tipos S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Níveis de decisão - hierarquia HTF'),
('Priorizar S/R por Timeframe','Habilidades Práticas','Leitura Estrutura','Habilidade','19-29','S/R HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','HTF > CTF > LTF sempre'),
('Reconhecer Gaps','Habilidades Práticas','Leitura Barras','Habilidade','08-11','Tipos Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','MAG/EG/MG/Corpo/Micro - diferentes significados'),
('Diferenciar EG vs MG','Habilidades Práticas','Leitura Barras','Habilidade','08-11','EG e MG',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Exaustão vs Projeção - impacta alvo'),
('Reconhecer MTR em Formação','Habilidades Práticas','Identificação Padrões','Habilidade Avançada','19-29','MTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','LH em topo / HL em fundo - mais difícil'),
('Identificar Cunhas','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','3 pushes com linhas convergentes'),
('Distinguir Cunha Boa de Ruim','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Qualidade Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Contexto da tendência - crucial'),
('Reconhecer Double Tops/Bottoms','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Duplos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','2 topos/fundos similares'),
('Identificar Head and Shoulders','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','OHO - maioria são minoritários'),
('Reconhecer Bull/Bear Flags','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Bandeiras',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correção que prepara nova perna'),
('Identificar Bandeiras Finais','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Bandeiras Finais',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Última antes TR - operação rentável'),
('Reconhecer Clímax','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Buying/Selling climax'),
('Identificar Clímax Consecutivos','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Clímax Consecutivo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','2+ seguidos - segundo falha'),
('Reconhecer Armadilhas','Habilidades Práticas','Identificação Padrões','Habilidade','19-29','Armadilhas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bull/Bear traps - fade'),
('Identificar BO Forte vs Fraco','Habilidades Práticas','Identificação Padrões','Habilidade','12-18','Qualidade BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap/grande barra/follow-through'),
('Contar Legs H1-H4 L1-L4','Habilidades Práticas','Leitura Estrutura','Habilidade','08-11','Contagem Legs',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Numerar pernas - timing'),
('Reconhecer H2/L2 como Entrada','Habilidades Práticas','Leitura Estrutura','Habilidade','08-11','H2/L2',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Segunda perna - contra desistem'),
('Identificar H4/L4 (exaustão)','Habilidades Práticas','Leitura Estrutura','Habilidade','08-11','H4/L4',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Quarta perna - alerta'),
('Determinar Major vs Minor Swings','Habilidades Práticas','Leitura Estrutura','Habilidade','08-11','Major e Minor',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tamanho relativo - importância do stop'),
('Ler Pressão de Mercado','Habilidades Práticas','Leitura Pressão','Habilidade','08-11','Tipos Pressão',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra/Venda/Equilíbrio'),
('Identificar Trapped Traders','Habilidades Práticas','Leitura Pressão','Habilidade','08-11','Trapped Traders',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Posições presas - força o mercado'),
('Calcular Movimento Projetado','Habilidades Práticas','Análise','Cálculo','19-29','MM',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Leg1=Leg2 / altura TR-BO'),
('Calcular Probabilidade do Setup','Habilidades Práticas','Análise','Cálculo','08-11','Probabilidade',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alta/Média/Baixa - contexto'),
('Calcular Risk:Reward','Habilidades Práticas','Análise','Cálculo','08-11','Risco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alvo/Stop ratio - mínimo 1:1.5'),
('Aplicar Regra 80%','Habilidades Práticas','Análise','Regras','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Reversões/BOs falham'),
('Aplicar Regra 70%','Habilidades Práticas','Análise','Regras','12-18','Regra 70%',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Teste linha canal'),
('Determinar Tipo de Ordem Correto','Habilidades Práticas','Execução Entrada','Habilidade','30-36','Stop/Limit/Market',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Stop vs Limit vs Market - contexto'),
('Posicionar Stop Loss Correto','Habilidades Práticas','Execução Stop','Habilidade Core','30-36','Stop Técnico',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Abaixo HL/acima LH - técnico não arbitrário'),
('Calcular Tamanho de Posição','Habilidades Práticas','Execução Entrada','Habilidade','30-36','Tamanho Posição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Risco fixo / distância stop = contratos'),
('Scale In em Ganhadora','Habilidades Práticas','Gestão Posição','Habilidade','30-36','Scale In OK',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Adicionar em lucro - confirmação'),
('Evitar Scale In em Perdedora','Habilidades Práticas','Gestão Posição','Habilidade','30-36','Scale In Perigo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','NUNCA adicionar em perda'),
('Mover Stop para Breakeven','Habilidades Práticas','Gestão Stop','Habilidade','30-36','Breakeven',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Após trade confirmar - protege entrada'),
('Aplicar Trailing Stop','Habilidades Práticas','Gestão Stop','Habilidade','30-36','Trailing Stop',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Seguir abaixo cada novo HL'),
('Sair por Premissa Mudada','Habilidades Práticas','Realização','Habilidade','30-36','Premissa Mudou',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Razão técnica não emocional'),
('Comprar Pullback em Alta','Habilidades Práticas','Operação Tendência','Habilidade','37-42','Compra Correção',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Com tendência'),
('Vender Rally em Baixa','Habilidades Práticas','Operação Tendência','Habilidade','37-42','Venda Rally',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Com tendência'),
('Operar Canal Estreito Alta','Habilidades Práticas','Operação Canal','Habilidade','37-42','Canal Estreito Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra pullback raso'),
('Operar Canal Estreito Baixa','Habilidades Práticas','Operação Canal','Habilidade','37-42','Canal Estreito Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Venda rally raso'),
('Operar Canal Amplo Alta','Habilidades Práticas','Operação Canal','Habilidade','37-42','Canal Amplo Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra zona inferior'),
('Operar Canal Amplo Baixa','Habilidades Práticas','Operação Canal','Habilidade','37-42','Canal Amplo Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Venda zona superior'),
('Comprar Metade Inferior TR','Habilidades Práticas','Operação TR','Habilidade','37-42','BLSHS',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Buy low - zona suporte'),
('Vender Metade Superior TR','Habilidades Práticas','Operação TR','Habilidade','37-42','BLSHS',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Sell high - zona resistência'),
('Apostar CONTRA BO em TR','Habilidades Práticas','Operação TR','Habilidade','37-42','Aposte Contra BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fade breakout'),
('Entrar em BO Forte','Habilidades Práticas','Operação BO','Habilidade','37-42','BO Forte',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Com gap/grande barra'),
('Aguardar Teste em BO Fraco','Habilidades Práticas','Operação BO','Habilidade','37-42','BO Fraco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pullback primeiro'),
('Operar MTR em Topos','Habilidades Práticas','Operação Reversão','Habilidade Avançada','37-42','MTR Topos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','LH setup - R:R 1:2'),
('Operar MTR em Fundos','Habilidades Práticas','Operação Reversão','Habilidade Avançada','37-42','MTR Fundos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','HL setup - R:R 1:2'),
('Operar na Abertura','Habilidades Práticas','Timing','Habilidade','43-46','Abertura',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Primeira hora - máxima volatilidade'),
('Identificar Reversão vs Tendência Abertura','Habilidades Práticas','Timing','Habilidade','43-46','Abertura',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','80% reversão / 20% tendência'),
('Procurar Mudança Fase Meio Dia','Habilidades Práticas','Timing','Habilidade','43-46','Meio Dia',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Transições após almoço'),
('Identificar Armadilhas Final Dia','Habilidades Práticas','Timing','Habilidade','43-46','Final Dia',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bull/Bear traps últimos 60min')
ON CONFLICT (conceito) DO UPDATE SET
  macro_categoria = EXCLUDED.macro_categoria,
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria,
  modulo_curso = EXCLUDED.modulo_curso,
  prerequisito = EXCLUDED.prerequisito,
  objetivo = EXCLUDED.objetivo,
  fonte_estudo = EXCLUDED.fonte_estudo,
  regras_operacionais = EXCLUDED.regras_operacionais,
  probabilidade = EXCLUDED.probabilidade,
  mercado_aplicavel = EXCLUDED.mercado_aplicavel,
  notas = EXCLUDED.notas;