INSERT INTO conceitos (conceito, macro_categoria, categoria, subcategoria, modulo_curso, prerequisito, conhecimento_atual, objetivo, data_estudo, tempo_investido_hrs, fonte_estudo, regras_operacionais, probabilidade, mercado_aplicavel, notas)
VALUES
('Tipos de Gráficos','Fundamentos','Terminologia Base','Conceitos Iniciais','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','5min/Diário/Semanal/Mensal'),
('Tempos Gráficos','Fundamentos','Terminologia Base','Conceitos Iniciais','01-07','Tipos de Gráficos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Relação entre timeframes'),
('Como Mercados Funcionam','Fundamentos','Terminologia Base','Conceitos Iniciais','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Leilão de preços e probing'),
('Definição Price Action','Fundamentos','Terminologia Base','Conceitos Iniciais','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Leitura pura do preço'),
('Pain Trade','Fundamentos','Terminologia Base','Conceitos Iniciais','01-07','Definição Price Action',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Movimento que causa máxima dor'),
('Média Móvel (MA/EMA)','Fundamentos','Indicadores','Ferramentas','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','EMA 20 períodos padrão Al Brooks'),
('Volume','Fundamentos','Indicadores','Ferramentas','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Confirmação de movimento'),
('Notícias e Eventos','Fundamentos','Fundamentos','Influências Externas','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fique fora durante notícias importantes'),
('Mercado Forex','Fundamentos','Forex','Mercado Específico','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Visão geral do Forex'),
('Sessões Forex','Fundamentos','Forex','Mercado Específico','01-07','Mercado Forex',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Londres/NY/Ásia - sobreposição importante'),
('Pip','Fundamentos','Forex','Terminologia Forex','01-07','Mercado Forex',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Menor variação de preço no Forex'),
('Pares de Moedas','Fundamentos','Forex','Terminologia Forex','01-07','Pip',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','EUR/USD, GBP/USD etc.'),
('Alavancagem Forex','Fundamentos','Forex','Terminologia Forex','01-07','Pares de Moedas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Risco amplificado'),
('Margens','Fundamentos','Forex','Terminologia Forex','01-07','Alavancagem Forex',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Depósito mínimo por posição'),
('Futuros vs Forex','Fundamentos','Forex','Comparativo','01-07','Mercado Forex',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Vantagens de cada mercado'),
('Emini S&P 500','Fundamentos','Emini','Mercado Específico','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Emini','Contrato futuro mais líquido - referência Al Brooks'),
('HFT (High Frequency Trading)','Fundamentos','Operando com Programas','Algoritmos','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Operação de alta frequência - parte do mercado'),
('Spoofing','Fundamentos','Operando com Programas','Algoritmos','01-07','HFT',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Ordens falsas para manipular preço'),
('Antecipação e HFTs','Fundamentos','Operando com Programas','Algoritmos','01-07','HFT',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','HFTs antecipam ordens grandes'),
('Corpo da Barra','Fundamentos','Anatomia da Barra','Estrutura','01-07','Tipos de Gráficos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Distância abertura-fechamento'),
('Sombra da Barra','Fundamentos','Anatomia da Barra','Estrutura','01-07','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Cauda superior e inferior'),
('Máxima e Mínima','Fundamentos','Anatomia da Barra','Estrutura','01-07','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Extremos da barra'),
('Abertura e Fechamento','Fundamentos','Anatomia da Barra','Estrutura','01-07','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pontos críticos de cada barra'),
('Trend Bar','Fundamentos','Tipos de Barra','Classificação','08-11','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Corpo grande com fechamento perto extremo'),
('Doji','Fundamentos','Tipos de Barra','Classificação','08-11','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Corpo pequeno indica indecisão'),
('Inside Bar (i)','Fundamentos','Tipos de Barra','Padrões de Barras','08-11','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Máxima/mínima dentro barra anterior'),
('Outside Bar (o)','Fundamentos','Tipos de Barra','Padrões de Barras','08-11','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Máxima/mínima engolfa barra anterior'),
('Reversal Bar','Fundamentos','Tipos de Barra','Classificação','08-11','Trend Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barra com sombra longa contrária'),
('Barra Grande/Média/Pequena','Fundamentos','Tamanho de Barra','Classificação','08-11','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Relativo ao contexto recente'),
('Barra de Tendência','Fundamentos','Classificação Funcional','Barras Funcionais','08-11','Trend Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barra alinhada com tendência'),
('Barra TR','Fundamentos','Classificação Funcional','Barras Funcionais','08-11','Doji',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barra de lateralidade'),
('Barra de Sinal','Fundamentos','Classificação Funcional','Barras Funcionais','08-11','Tipos de Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barra que precede entrada'),
('Barra de Entrada','Fundamentos','Classificação Funcional','Barras Funcionais','08-11','Barra de Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Onde executar ordem'),
('Barra de Surpresa','Fundamentos','Classificação Funcional','Barras Funcionais','08-11','Barra Grande',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Movimento inesperado forte'),
('Barra de Desistência','Fundamentos','Classificação Funcional','Barras Funcionais','08-11','Trend Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Traders desistem da direção - reversão minoritária'),
('Padrão ii (inside-inside)','Fundamentos','Padrões de Barras','Compostos','08-11','Inside Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','2 inside bars consecutivas - compressão extrema'),
('Padrão ioi','Fundamentos','Padrões de Barras','Compostos','08-11','Inside Bar e Outside Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Inside-outside-inside - indecisão'),
('Padrão oo','Fundamentos','Padrões de Barras','Compostos','08-11','Outside Bar',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','2 outside bars - volatilidade extrema - fique fora'),
('Higher High (HH)','Fundamentos','Relação Entre Barras','Estrutura','08-11','Máxima e Mínima',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Máxima acima da anterior'),
('Higher Low (HL)','Fundamentos','Relação Entre Barras','Estrutura','08-11','Máxima e Mínima',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mínima acima da anterior'),
('Lower High (LH)','Fundamentos','Relação Entre Barras','Estrutura','08-11','Máxima e Mínima',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Máxima abaixo da anterior'),
('Lower Low (LL)','Fundamentos','Relação Entre Barras','Estrutura','08-11','Máxima e Mínima',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mínima abaixo da anterior'),
('Equal High (EH)','Fundamentos','Relação Entre Barras','Estrutura','08-11','Máxima e Mínima',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Máxima igual à anterior - duplo topo'),
('Equal Low (EL)','Fundamentos','Relação Entre Barras','Estrutura','08-11','Máxima e Mínima',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mínima igual à anterior - duplo fundo'),
('Definição de Gap','Fundamentos','Gaps','Tipos de Gap','08-11','Corpo da Barra',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Espaço entre barras consecutivas'),
('MAG (Moving Average Gap)','Fundamentos','Gaps','Tipos de Gap','08-11','Definição de Gap e MA',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap entre preço e média móvel - tendência forte'),
('EG (Exhaustion Gap)','Fundamentos','Gaps','Tipos de Gap','08-11','Definição de Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap de exaustão - possível reversão'),
('MG (Measuring Gap)','Fundamentos','Gaps','Tipos de Gap','08-11','Definição de Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap de projeção - continuação com alvo igual'),
('Gap de Corpo','Fundamentos','Gaps','Tipos de Gap','08-11','Definição de Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap entre corpos (não sombras) - força máxima'),
('Micro Gap','Fundamentos','Gaps','Tipos de Gap','08-11','Definição de Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap minúsculo entre barras'),
('Gap de Abertura','Fundamentos','Gaps','Tipos de Gap','08-11','Definição de Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap na abertura do dia - 70-80% fechado'),
('Gap como Força','Fundamentos','Gaps','Significado','08-11','Tipos de Gap',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Indica pressão institucional forte'),
('Padrão Escada','Fundamentos','Gaps','Significado','08-11','MAG',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Série de gaps na mesma direção - tendência forte'),
('Swing High','Fundamentos','Linhas Horizontais','S/R Estático','08-11','Higher High',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Topo significativo - zona de resistência'),
('Swing Low','Fundamentos','Linhas Horizontais','S/R Estático','08-11','Lower Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fundo significativo - zona de suporte'),
('Números Redondos','Fundamentos','Linhas Horizontais','S/R Estático','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Níveis psicológicos: 00/50/000 - magneto'),
('Linha de Tendência','Fundamentos','Linhas Diagonais','S/R Dinâmico','08-11','Swing High e Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Conecta pivots - violação = sinal fraqueza'),
('Linha de Canal','Fundamentos','Linhas Diagonais','S/R Dinâmico','08-11','Linha de Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Paralela à linha de tendência'),
('MA como Linha Dinâmica','Fundamentos','Linhas Dinâmicas','S/R Dinâmico','08-11','Média Móvel',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','EMA20 = suporte/resistência dinâmica'),
('Equação do Trader','Fundamentos','Matemática','Fundamentos Matemáticos','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Edge = Prob × Reward - Risk'),
('Edge (Vantagem)','Fundamentos','Matemática','Fundamentos Matemáticos','01-07','Equação do Trader',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Expectativa matemática positiva no longo prazo'),
('Probabilidade','Fundamentos','Matemática','Fundamentos Matemáticos','01-07','Equação do Trader',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Chance de sucesso estimada do setup'),
('Recompensa (Reward)','Fundamentos','Matemática','Fundamentos Matemáticos','01-07','Equação do Trader',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Potencial de lucro em relação ao risco'),
('Risco','Fundamentos','Matemática','Fundamentos Matemáticos','01-07','Equação do Trader',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Potencial de perda = distância até stop'),
('Três Variáveis do Trade','Fundamentos','Matemática','Fundamentos Matemáticos','01-07','Equação do Trader',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Prob/Reward/Risk - ajustar 1 afeta outras 2'),
('Z-score','Fundamentos','Matemática Avançada','Estatística','01-07','Três Variáveis',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Medida estatística de desvio - série de resultados'),
('Probabilidade Alta (70-90%)','Fundamentos','Níveis de Probabilidade','Referências','08-11','Probabilidade',0,10,NULL,NULL,'Livro/Video/Arvore','70-90%','Universal','Universal','Com tendência forte e setup perfeito'),
('Probabilidade Média (50-60%)','Fundamentos','Níveis de Probabilidade','Referências','08-11','Probabilidade',0,10,NULL,NULL,'Livro/Video/Arvore','50-60%','Universal','Universal','Setup padrão sem contexto excepcional'),
('Probabilidade Baixa (40-50%)','Fundamentos','Níveis de Probabilidade','Referências','08-11','Probabilidade',0,10,NULL,NULL,'Livro/Video/Arvore','40-50%','Universal','Universal','Contra-tendência ou scalp de risco'),
('Risk:Reward Mínimo 1:1.5','Fundamentos','Matemática','Gestão Financeira','08-11','Risco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mínimo aceitável para qualquer trade'),
('Risk:Reward Swing 1:2','Fundamentos','Matemática','Gestão Financeira','08-11','Risco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Padrão para swing trade'),
('Regra dos 80% - Reversões Falham','Fundamentos','Regras Estatísticas','Probabilidade','12-18','Probabilidade',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','80% tentativas reversão falham - favor tendência'),
('Regra dos 80% - Rompimentos Falham','Fundamentos','Regras Estatísticas','Probabilidade','12-18','Probabilidade',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','80% breakouts de TR falham - apostem contra'),
('Regra dos 80% - Inércia','Fundamentos','Regras Estatísticas','Probabilidade','12-18','Regra 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Mercado tende a continuar na direção atual'),
('Regra dos 70% - Teste de Canal','Fundamentos','Regras Estatísticas','Probabilidade','12-18','Linha de Canal',0,10,NULL,NULL,'Livro/Video/Arvore','70%','Universal','Universal','70% dos movimentos testam linha oposta do canal'),
('Regra 40-60 em TR','Fundamentos','Regras Estatísticas','Probabilidade','12-18','Probabilidade Média',0,10,NULL,NULL,'Livro/Video/Arvore','40-60%','Universal','Universal','Probabilidade ~50% no meio de Trading Range'),
('Operações Perfeitas Não Existem','Fundamentos','Mentalidade','Fundamentos','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Aceitar imperfeição - contexto sempre ambíguo'),
('Disciplina','Psicologia','Traços de Sucesso','Psicologia Positiva','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Seguir regras consistentemente - base de tudo'),
('Paciência','Psicologia','Traços de Sucesso','Psicologia Positiva','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Aguardar setup de qualidade - não forçar'),
('Confiança no Sistema','Psicologia','Traços de Sucesso','Psicologia Positiva','01-07','Disciplina e Paciência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Confiar no edge mesmo após perdas'),
('Confortável com Incerteza','Psicologia','Traços de Sucesso','Psicologia Positiva','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Aceitar resultado probabilístico'),
('Gestão de Medo','Psicologia','Estados Destrutivos','Psicologia Negativa','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Controlar medo que impede entrar/sair correto'),
('Gestão de Ambição/Ganância','Psicologia','Estados Destrutivos','Psicologia Negativa','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não segurar posição além do plano'),
('Gestão de FOMO','Psicologia','Estados Destrutivos','Psicologia Negativa','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fear Of Missing Out - não entrar tarde'),
('Evitar Decisões Estúpidas','Psicologia','Estados Destrutivos','Psicologia Negativa','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não operar por impulso ou emoção'),
('Aceitar Incerteza','Psicologia','Gestão Emocional','Habilidades Emocionais','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Resultado sempre probabilístico - aceitar'),
('Não Vingar Perdas','Psicologia','Gestão Emocional','Habilidades Emocionais','01-07','Aceitar Incerteza',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pause 10 min após stop - não revenge trade'),
('Aprender com Perdas','Psicologia','Gestão Emocional','Habilidades Emocionais','01-07','Não Vingar Perdas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Análise de erros sem julgamento'),
('Não Comemorar Cedo','Psicologia','Gestão Emocional','Habilidades Emocionais','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Lucro aberto não é seu - proteger com trailing'),
('Proteger Ganhos','Psicologia','Gestão Emocional','Habilidades Emocionais','01-07','Não Comemorar Cedo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Trailing stops e realizações parciais'),
('Falsas Crenças','Psicologia','Crenças Limitantes','Psicologia Cognitiva','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identificar e eliminar crenças que atrapalham'),
('Overtrading','Psicologia','Erros Comuns','Comportamentos Destrutivos','01-07','Paciência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Operar demais - qualidade > quantidade'),
('Revenge Trading','Psicologia','Erros Comuns','Comportamentos Destrutivos','01-07','Não Vingar Perdas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tentar recuperar perda no calor do momento'),
('Gerenciamento Ruim de Trade','Psicologia','Erros Comuns','Comportamentos Destrutivos','01-07','Disciplina',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não seguir o plano definido antes da entrada'),
('Segurando Perdedores Muito Tempo','Psicologia','Gestão de Perdas','Erros de Saída','47-50','Gestão de Medo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Esperança mata contas - stop é obrigatório'),
('Realizando Lucros Muito Rápido','Psicologia','Gestão de Perdas','Erros de Saída','47-50','Gestão de Ambição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Sair antes do alvo por medo de perder ganho'),
('Perdendo Depois de Aumentar Posição','Psicologia','Gestão de Perdas','Erros de Escalonamento','47-50','Segurando Perdedores',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Scale in em perdedora - erro fatal'),
('Quatro Fases do Mercado','Contexto','Ciclo de Mercado','Framework Central','12-18','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tendência/Canal/TR/Rompimento - ciclo contínuo'),
('Fase Tendência','Contexto','Fases','Ciclo','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Direção clara - HH/HL ou LH/LL'),
('Fase Canal','Contexto','Fases','Ciclo','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entre 2 linhas paralelas com direção')
ON CONFLICT (conceito) DO UPDATE SET
  macro_categoria = EXCLUDED.macro_categoria,
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria,
  modulo_curso = EXCLUDED.modulo_curso,
  prerequisito = EXCLUDED.prerequisito,
  objetivo = EXCLUDED.objetivo,
  fonte_estudo = EXCLUDED.fonte_estudo,
  regras_operacionais = EXCLUDED.regras_operacionais,
  probabilidade = EXCLUDED.probabilidade,
  mercado_aplicavel = EXCLUDED.mercado_aplicavel,
  notas = EXCLUDED.notas;