INSERT INTO conceitos (conceito, macro_categoria, categoria, subcategoria, modulo_curso, prerequisito, conhecimento_atual, objetivo, data_estudo, tempo_investido_hrs, fonte_estudo, regras_operacionais, probabilidade, mercado_aplicavel, notas)
VALUES
('Fase Lateralidade (TR)','Contexto','Fases','Ciclo','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Range-bound - sem direção clara'),
('Fase Rompimento','Contexto','Fases','Ciclo','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Breakout - início nova tendência ou falha'),
('Transição por Correção','Contexto','Transições','Ciclo','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pullback evolui para TR'),
('Transição por Rompimento','Contexto','Transições','Ciclo','12-18','Quatro Fases',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BO inicia nova fase'),
('Inércia do Mercado','Contexto','Ciclo','Propriedades','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Tendência a continuar > reverter'),
('Mercados Resistem à Mudança','Contexto','Ciclo','Propriedades','12-18','Inércia',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Favor da continuação sempre'),
('Probing Contínuo','Contexto','Ciclo','Propriedades','12-18','Como Mercados Funcionam',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mercado testa S/R constantemente'),
('Conceito Always In Direction','Contexto','Always In','Framework Central','12-18','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Framework central Al Brooks - base de tudo'),
('Always In Long (AIL)','Contexto','Always In Direction','Estados','12-18','Conceito Always In Direction',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Viés compra - compradores no controle'),
('Always In Short (AIS)','Contexto','Always In Direction','Estados','12-18','Conceito Always In Direction',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Viés venda - vendedores no controle'),
('Always In Clara','Contexto','Always In Clareza','Estados','12-18','Always In Direction',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fácil determinar direção - opere a favor'),
('Always In Confusa','Contexto','Always In Clareza','Estados','12-18','Always In Direction',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Difícil determinar - é Trading Range'),
('Decisões Binárias','Contexto','Always In','Princípio','12-18','Conceito Always In Direction',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Long ou Short - simplificar processo decisão'),
('BLSHS - Buy Low','Contexto','BLSHS','Modo TR','12-18','Always In Confusa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Comprar em baixo de TR - zona suporte'),
('BLSHS - Sell High','Contexto','BLSHS','Modo TR','12-18','Always In Confusa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Vender em topo de TR - zona resistência'),
('BLSHS - Scalp','Contexto','BLSHS','Modo TR','12-18','Always In Confusa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entradas rápidas scalp em TR'),
('Estrutura de Tendência','Contexto','Tendência','Estrutura','12-18','HH/HL/LH/LL',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Swings/Pernas/Pivots compõem tendência'),
('Tendência Alta - Higher Lows','Contexto','Tendência Alta','Identificação','12-18','Higher Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Série de HLs = compradores controlam'),
('Compradores Controlam','Contexto','Tendência Alta','Psicologia','12-18','Tendência Alta HL',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bulls no comando - não opere contra'),
('Micro Canal Alta','Contexto','Tendência Alta','Tipos','12-18','Tendência Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mais forte - sem correção - pode ser clímax'),
('Canal Estreito Alta','Contexto','Tendência Alta','Tipos','12-18','Tendência Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correções rasas 1-3 barras - não toca EMA20'),
('Canal Amplo Alta','Contexto','Tendência Alta','Tipos','12-18','Tendência Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correções profundas 50%+ - toca EMA20'),
('Tendência Baixa - Lower Highs','Contexto','Tendência Baixa','Identificação','12-18','Lower High',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Série de LHs = vendedores controlam'),
('Vendedores Controlam','Contexto','Tendência Baixa','Psicologia','12-18','Tendência Baixa LH',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bears no comando - não opere contra'),
('Micro Canal Baixa','Contexto','Tendência Baixa','Tipos','12-18','Tendência Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mais forte - sem correção - pode ser clímax'),
('Canal Estreito Baixa','Contexto','Tendência Baixa','Tipos','12-18','Tendência Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correções rasas - muito forte'),
('Canal Amplo Baixa','Contexto','Tendência Baixa','Tipos','12-18','Tendência Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correções profundas - inclui dois lados'),
('Tendência Forte - Características','Contexto','Qualidade Tendência','Avaliação','12-18','Estrutura Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barras grandes/gaps/micro canal/sem overlap'),
('Tendência Fraca - Características','Contexto','Qualidade Tendência','Avaliação','12-18','Estrutura Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barras pequenas/dojis/muito overlap'),
('Quando Não Clara é TR','Contexto','Tendência','Diagnóstico','12-18','Always In Confusa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Dúvida = lateralidade - não force'),
('Rompimento Significa Mais Forte','Contexto','Tendência','Diagnóstico','12-18','Fase Rompimento',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BO indica força renovada na direção'),
('Tendências Tentam Reverter (80% falham)','Contexto','Tendência','Estatística','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','80% das tentativas de reversão falham'),
('Tendência da Abertura','Contexto','Tendência','Timing','43-46','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore','20%','Universal','Universal','20% dos dias têm tendência desde abertura'),
('Tendências Respeitam Correções Major','Contexto','Tendência','Comportamento','12-18','Estrutura Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não quebram swings importantes em tendência forte'),
('Novas Tendências Começam em Antigas','Contexto','Tendência','Comportamento','12-18','Estrutura Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Reversão de tendência anterior - breakout'),
('Definição Canal','Contexto','Canais','Estrutura','12-18','Linha de Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','2 linhas paralelas contendo movimento direcional'),
('2 Pontos Necessários','Contexto','Canais','Construção','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mínimo para traçar linha'),
('Canal Alta Estreito','Contexto','Tipos Canal','Identificação','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alta com correções rasas - forte'),
('Canal Alta Amplo','Contexto','Tipos Canal','Identificação','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alta com correções profundas - inclui ambos lados'),
('Canal Baixa Estreito','Contexto','Tipos Canal','Identificação','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Baixa com correções rasas - forte'),
('Canal Baixa Amplo','Contexto','Tipos Canal','Identificação','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Baixa com correções profundas'),
('Micro Canal - Tendência Mais Forte','Contexto','Micro Canal','Características','12-18','Canal Estreito',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Sem correções - força máxima - pode ser clímax'),
('Micro Canal - Pode Ser Clímax','Contexto','Micro Canal','Características','12-18','Micro Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','8+ barras sem romper = clímax possível'),
('Teste Linha Canal (70%)','Contexto','Comportamento Canal','Estatística','12-18','Regra 70%',0,10,NULL,NULL,'Livro/Video/Arvore','70%','Universal','Universal','70% dos movimentos testam linha oposta'),
('Overshoot','Contexto','Comportamento Canal','Padrão','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Rompe linha e volta - sinal exaustão'),
('Undershoot','Contexto','Comportamento Canal','Padrão','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não alcança linha - força diminuindo'),
('Evolução Canal para TR','Contexto','Comportamento Canal','Transição','12-18','Definição Canal e TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Canal amplo inevitavelmente vira TR'),
('Como Traçar Canais','Contexto','Canais Prático','Técnica','12-18','Linha de Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Técnica de desenho das linhas'),
('Rompimentos Canal Geralmente Falham','Contexto','Rompimentos Canal','Estatística','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Maioria dos BOs de canal falham'),
('BO Início Tendência Mais Sucesso','Contexto','Rompimentos Canal','Timing','12-18','Rompimentos Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Timing melhor no início da tendência'),
('Maioria Canais São Cunhas','Contexto','Canais','Natureza','12-18','Definição Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Linhas tendem a convergir'),
('Canal Amplo ou TR','Contexto','Canais','Diagnóstico','12-18','Canal Amplo e TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Difícil distinguir - mesmos princípios'),
('Toda TR tem Canal Alta e Canal Baixa','Contexto','Canais e TR','Perspectiva','12-18','Canal e TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Perspectivas diferentes do mesmo movimento'),
('Definição TR','Contexto','Lateralidade','Framework','12-18','Always In Confusa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Trading Range - lateralidade'),
('TR - Correção vs Lateralidade','Contexto','Lateralidade','Distinção','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correção = temporária; TR = estabelecida'),
('TR - Confusão e Decepção','Contexto','Lateralidade','Psicologia','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Marca registrada da TR - decepciona ambos lados'),
('TTR (Tight Trading Range)','Contexto','Amplitude TR','Tipos','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','TR estreita = compressão = explosão iminente'),
('TR Ampla','Contexto','Amplitude TR','Tipos','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Range largo 20+ pontos - setups claros'),
('BOM (Breakout Mode)','Contexto','Modos TR','Modos de Mercado','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','TR nova - aguarda breakout - use stop orders'),
('LOM (Limit Order Market)','Contexto','Modos TR','Modos de Mercado','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','TR estabelecida 15+ barras - fade extremos'),
('Posição no Topo TR','Contexto','Posição TR','Zonas','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Perto resistência - viés venda'),
('Posição no Meio TR','Contexto','Posição TR','Zonas','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Zona neutra 50/50 - NÃO opere'),
('Posição no Fundo TR','Contexto','Posição TR','Zonas','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Perto suporte - viés compra'),
('Metade Superior TR','Contexto','Posição TR','Zonas','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Viés venda mas aguarde topo'),
('Metade Inferior TR','Contexto','Posição TR','Zonas','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Viés compra mas aguarde fundo'),
('TR Contém Setups Ambos Lados','Contexto','Características TR','Natureza','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Buy e sell signals presentes simultaneamente'),
('Pernas na TR (não tendência)','Contexto','Características TR','Natureza','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Movimentos dentro range - não contar como legs'),
('Platôs','Contexto','Características TR','Padrões','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Consolidações horizontais dentro da TR'),
('Efeito Vácuo','Contexto','Comportamento TR','Fenômeno','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Preço atraído para S/R forte - não entre durante'),
('Lógica Perversa da TR','Contexto','Comportamento TR','Psicologia','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Faz o oposto do esperado - apostadores em tendência perdem'),
('Não Aposte NO Rompimento de TR','Contexto','Comportamento TR','Regra','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','80% dos BOs de TR falham'),
('Aposte CONTRA Rompimento de TR','Contexto','Comportamento TR','Regra','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Fade o breakout - estratégia vencedora na TR'),
('Sinais Antecipados de TR','Contexto','Lateralidade','Diagnóstico','12-18','TR Fraca',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Identificar cedo para ajustar estratégia'),
('Toda TR É Bandeira Potencial','Contexto','Lateralidade','Perspectiva','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pode continuar tendência anterior'),
('TR Eventualmente Rompe','Contexto','Lateralidade','Certeza','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Questão de quando - posicione para o BO'),
('Definição Rompimento (BO)','Contexto','Rompimentos','Framework','12-18','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Breakout - preço sai da estrutura atual'),
('Rompimento de Alta','Contexto','Tipos BO','Direção','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bullish breakout'),
('Rompimento de Baixa','Contexto','Tipos BO','Direção','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bearish breakout'),
('BO Forte - Com Gap de Corpo','Contexto','Qualidade BO Forte','Identificação','12-18','Definição BO e Gap',0,10,NULL,NULL,'Livro/Video/Arvore','60-70%','Universal','Universal','Gap entre corpos = força máxima'),
('BO Forte - Grande Barra','Contexto','Qualidade BO Forte','Identificação','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore','60-70%','Universal','Universal','Barra impulso 2x+ média = força'),
('BO Forte - Follow-Through','Contexto','Qualidade BO Forte','Identificação','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore','60-70%','Universal','Universal','Continuidade imediata após BO'),
('BO Forte - Sem Retração em 3 Barras','Contexto','Qualidade BO Forte','Identificação','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore','60-70%','Universal','Universal','Não volta nas 3 barras seguintes'),
('BO Forte - Segunda Perna Provável','Contexto','Qualidade BO Forte','Consequência','12-18','BO Forte',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Leg 1 = Leg 2 após correção mínima'),
('BO Fraco - Características','Contexto','Qualidade BO Fraco','Identificação','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Pavios grandes/sem gap/pequeno/sem follow - 80% falha'),
('Resultado BO - Sucesso (20%)','Contexto','Resultado BO','Estatística','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore','20%','Universal','Universal','Inicia nova tendência - raro'),
('Resultado BO - Falha (80%)','Contexto','Resultado BO','Estatística','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Maioria falha - apostem contra'),
('Reversão É Rompimento','Contexto','Rompimentos','Perspectiva','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BO da tendência anterior em sentido oposto'),
('BO Pode Começar Pequeno','Contexto','Rompimentos','Característica','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não precisa ser explosivo no início'),
('Segunda Perna Comum Após BO','Contexto','Rompimentos','Estrutura','12-18','BO Forte',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','TBTL - 10 barras 2 pernas usual'),
('Rompimentos de TR','Contexto','Rompimentos','Contexto','12-18','TR e BO',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','BO de range - 80% falham'),
('Teste de Rompimento','Contexto','Rompimentos','Comportamento','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pullback ao ponto do BO - normal e esperado'),
('Falha BO - Retomada Tendência','Contexto','Falha BO','Resultados','12-18','Resultado BO Falha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Volta direção anterior'),
('Falha BO - Reversão Completa','Contexto','Falha BO','Resultados','12-18','Resultado BO Falha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Inverte direção - MTR possível'),
('BO como EG ou MG','Contexto','Rompimentos','Gaps','12-18','EG e MG',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Após BO: exaustão (EG) ou projeção (MG)'),
('BO Fraco = TR em Breve','Contexto','Rompimentos','Consequência','12-18','BO Fraco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Sem força = lateralidade próxima'),
('BO Geralmente Segue Armadilha','Contexto','Rompimentos','Sequência','12-18','Armadilhas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Trap precede BO verdadeiro'),
('Rompimento Tardio','Contexto','Rompimentos','Timing','12-18','Definição BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Final de tendência - não entre tarde'),
('Definição Leg (Perna)','Contexto','Legs e Swings','Estrutura','12-18','Estrutura Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Movimento direcional entre dois pivots'),
('Primeira Perna (Leg 1)','Contexto','Legs','Estrutura','12-18','Definição Leg',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Primeiro impulso direcional'),
('Segunda Perna (Leg 2)','Contexto','Legs','Estrutura','12-18','Primeira Perna',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Geralmente igual a Leg 1 - Measured Move')
ON CONFLICT (conceito) DO UPDATE SET
  macro_categoria = EXCLUDED.macro_categoria,
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria,
  modulo_curso = EXCLUDED.modulo_curso,
  prerequisito = EXCLUDED.prerequisito,
  objetivo = EXCLUDED.objetivo,
  fonte_estudo = EXCLUDED.fonte_estudo,
  regras_operacionais = EXCLUDED.regras_operacionais,
  probabilidade = EXCLUDED.probabilidade,
  mercado_aplicavel = EXCLUDED.mercado_aplicavel,
  notas = EXCLUDED.notas;