INSERT INTO conceitos (conceito, macro_categoria, categoria, subcategoria, modulo_curso, prerequisito, conhecimento_atual, objetivo, data_estudo, tempo_investido_hrs, fonte_estudo, regras_operacionais, probabilidade, mercado_aplicavel, notas)
VALUES
('Leg 1 = Leg 2 (Measured Move)','Contexto','Legs','Matemática','12-18','Segunda Perna',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Projeção mais confiável do Price Action'),
('Pivot Alto (Swing High)','Contexto','Pivots','Estrutura','12-18','Swing High',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Topo de swing - S/R potencial'),
('Pivot Baixo (Swing Low)','Contexto','Pivots','Estrutura','12-18','Swing Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fundo de swing - S/R potencial'),
('Correção (Pullback)','Contexto','Correções','Estrutura','12-18','Estrutura Tendência',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Retração temporária na tendência'),
('Major High/Low','Contexto','Classificação Major','Pivots','12-18','Pivots',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pivots importantes - referência principal'),
('Minor High/Low','Contexto','Classificação Minor','Pivots','12-18','Pivots',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pivots menores - referência secundária'),
('Contagem H1/L1','Contexto','Contagem Legs','Ferramenta','08-11','Legs',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Primeira máxima/mínima após correção'),
('Contagem H2/L2','Contexto','Contagem Legs','Ferramenta','08-11','H1/L1',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Segunda tentativa - traders contra saem'),
('Contagem H3/L3','Contexto','Contagem Legs','Ferramenta','08-11','H2/L2',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Terceira perna - pode formar cunha'),
('Contagem H4/L4','Contexto','Contagem Legs','Ferramenta','08-11','H3/L3',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Quarta perna - atenção provável exaustão'),
('Tempos Gráficos Afetam Legs','Contexto','Legs','Perspectiva','12-18','Tempos Gráficos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','HTF tem legs maiores - contexto muda'),
('Correção Rasa (sinal de força)','Contexto','Tipos Correção','Avaliação','12-18','Correção',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','1-3 barras - não toca EMA - força máxima'),
('Correção Profunda (sinal de fraqueza)','Contexto','Tipos Correção','Avaliação','12-18','Correção',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','50%+ - toca EMA - força diminuindo'),
('Correção 50%','Contexto','Tipos Correção','Matemática','12-18','Correção',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Metade do movimento - S/R matemático'),
('Correção Sem Fim (vira TR)','Contexto','Tipos Correção','Transformação','12-18','Correção e TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Perde momento e estabelece lateralidade'),
('Correção Majoritária vs Minoritária','Contexto','Correções','Classificação','12-18','Major e Minor',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tamanho relativo ao contexto'),
('Toda Correção É Bandeira Potencial','Contexto','Correções','Perspectiva','12-18','Correção',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pode continuar tendência após correção'),
('Tipos de Pressão','Contexto','Pressão','Framework','08-11','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra/Venda/Equilíbrio - psicologia do mercado'),
('Pressão - Manifestação Visual','Contexto','Pressão','Leitura','08-11','Tipos de Pressão',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap/Barras grandes/Sequência direcional'),
('Compradores/Vendedores Fortes/Fracos','Contexto','Pressão','Avaliação','08-11','Tipos de Pressão',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Força relativa dos participantes'),
('Trapped Traders','Contexto','Pressão','Psicologia','08-11','Armadilhas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Traders presos na direção errada - força o mercado'),
('Emboscados','Contexto','Pressão','Psicologia','08-11','Trapped Traders',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Ambushed - presos contra a tendência'),
('Traders Desapontados','Contexto','Pressão','Psicologia','08-11','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Disappointed - perderam a tendência'),
('Definição S/R','Contexto','Suporte e Resistência','Framework','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Zonas de decisão - preço reage aqui'),
('S/R Controlam Preço (não notícias)','Contexto','S/R','Princípio','19-29','Definição S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Notícias são pretexto - S/R é causa'),
('Tipos de S/R','Contexto','S/R','Tipos','19-29','Definição S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Swing/MA/Números Redondos/Linha Canal'),
('S/R de HTF Mais Importante','Contexto','S/R Origem','Hierarquia','19-29','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Timeframe maior > menor sempre'),
('S/R Testado vs Não Testado','Contexto','S/R Nível','Histórico','19-29','Definição S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Testado = confirmado; Não testado = mais forte'),
('S/R Respeitado vs Violado','Contexto','S/R Reação','Resultado','19-29','Definição S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Hold = respeitado; Break = violado'),
('Teste S/R - Sucesso/Falha','Contexto','S/R Teste','Resultado','19-29','Definição S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Hold ou break - define próxima fase'),
('Segunda Tentativa em S/R','Contexto','S/R Teste','Padrão','19-29','Teste S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Teste duplo - mais confiável'),
('Teste Tardio de S/R','Contexto','S/R Teste','Timing','43-46','Teste S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tarde no dia - common pattern'),
('Compradores Precisam de HL','Contexto','S/R','Requisito','12-18','Higher Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Para continuar alta - HL é o sinal'),
('Vendedores Precisam de LH','Contexto','S/R','Requisito','12-18','Lower High',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Para continuar baixa - LH é o sinal'),
('Clímax Sempre Termina em S/R','Contexto','S/R','Relação com Clímax','19-29','Clímax e S/R',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Exaustão sempre em nível significativo'),
('Movimentos Projetados (MM)','Contexto','MM','Matemática','19-29','Leg1=Leg2',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Measured moves - ferramenta principal de alvo'),
('MM - Perna 1 = Perna 2','Contexto','MM','Cálculo','19-29','Legs',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Primeira perna projeta segunda'),
('MM - Altura TR','Contexto','MM','Cálculo','19-29','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Altura do range como alvo do BO'),
('MM - Altura BO','Contexto','MM','Cálculo','19-29','BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tamanho do breakout como próximo alvo'),
('MM - Uso para Alvos','Contexto','MM','Aplicação','19-29','MM',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Onde realizar parcial ou total'),
('MM - Uso para Stops','Contexto','MM','Aplicação','19-29','MM',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Catastrophe stop baseado em MM'),
('Definição Barra de Sinal','Padrões','Barras de Sinal','Conceito','08-11','Barra de Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barra que precede e autoriza entrada'),
('Qualidade de Sinal - Forte','Padrões','Barras de Sinal','Avaliação','08-11','Barra de Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Corpo grande/fechamento extremo/pavio pequeno contrário'),
('Qualidade de Sinal - Fraca','Padrões','Barras de Sinal','Avaliação','08-11','Barra de Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Corpo pequeno/sombra grande/Doji - reduza posição'),
('Sinais Ruins (evitar)','Padrões','Barras de Sinal','Avaliação','08-11','Qualidade Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Contra contexto/Doji em TR/muito tarde'),
('Confirmação - Primeiro Sinal','Padrões','Confirmação','Timing','08-11','Barra de Sinal',0,10,NULL,NULL,'Livro/Video/Arvore','40-50%','Universal','Universal','Primeira tentativa - menor probabilidade'),
('Confirmação - Segundo Sinal (melhor)','Padrões','Confirmação','Timing','08-11','Primeiro Sinal',0,10,NULL,NULL,'Livro/Video/Arvore','60-70%','Universal','Universal','Contra desistiram - maior probabilidade'),
('Confirmação - Terceiro Sinal','Padrões','Confirmação','Timing','08-11','Segundo Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pode ser exaustão ou cunha - cuidado'),
('Sinal Com Tendência (melhor)','Padrões','Contexto Sinal','Qualidade','08-11','Tendência',0,10,NULL,NULL,'Livro/Video/Arvore','60-80%','Universal','Universal','Probabilidade alta - favor da inércia'),
('Sinal Contra Tendência','Padrões','Contexto Sinal','Qualidade','08-11','Tendência',0,10,NULL,NULL,'Livro/Video/Arvore','40-50%','Universal','Universal','Precisa sinal muito forte - R:R maior'),
('Sinal Em TR','Padrões','Contexto Sinal','Qualidade','08-11','TR',0,10,NULL,NULL,'Livro/Video/Arvore','50%','Universal','Universal','BLSHS - extremos do range apenas'),
('Definição Setup','Padrões','Setups','Conceito','08-11','Contexto + Sinal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Contexto + Barra Sinal = Setup'),
('Setup Fraco (precisa mais confirmação)','Padrões','Setups','Avaliação','08-11','Definição Setup',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Baixa probabilidade - reduza ou pule'),
('Apostar Contra Setups Fracos','Padrões','Setups','Estratégia','08-11','Setup Fraco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fade - contra direção do setup fraco'),
('Contagem de Barras','Padrões','Contagem','Ferramenta','08-11','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','H1-H4 / L1-L4 - contar pernas'),
('TBTL (Ten Bars Two Legs)','Padrões','Contagem','Regra','08-11','Contagem Barras',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','~10 barras 2 pernas após clímax antes novo setup'),
('Reversões Consecutivas H4/L4','Padrões','Contagem','Padrão','08-11','H4/L4',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Após 4 pernas - provável reversão ou TR'),
('Bull Flag - Definição','Padrões','Bandeiras','Continuação','19-29','Tendência Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correção em alta - espera nova perna'),
('Topo Duplo como Bull Flag','Padrões','Bull Flag','Tipos','19-29','Bull Flag e Duplo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','DT em correção de alta - sinal continua'),
('Cunha como Bull Flag','Padrões','Bull Flag','Tipos','19-29','Bull Flag e Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Wedge down em alta - 3 pernas baixa'),
('Canal Baixa como Bull Flag','Padrões','Bull Flag','Tipos','19-29','Bull Flag e Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bear channel em alta - bandeira clássica'),
('Bear Flag - Definição','Padrões','Bandeiras','Continuação','19-29','Tendência Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correção em baixa - espera nova perna'),
('Fundo Duplo como Bear Flag','Padrões','Bear Flag','Tipos','19-29','Bear Flag e Duplo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','DB em correção de baixa'),
('Cunha como Bear Flag','Padrões','Bear Flag','Tipos','19-29','Bear Flag e Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Wedge up em baixa - 3 pernas alta'),
('Canal Alta como Bear Flag','Padrões','Bear Flag','Tipos','19-29','Bear Flag e Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Bull channel em baixa'),
('Bandeiras Finais - Definição','Padrões','Bandeiras','Especial','19-29','Bandeiras',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Última bandeira antes da TR - operação mais rentável'),
('Bandeiras Finais - Rasas','Padrões','Bandeiras Finais','Características','19-29','Bandeiras Finais',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correção pequena < 10 barras'),
('Bandeiras Finais - Com ii','Padrões','Bandeiras Finais','Características','19-29','Bandeiras Finais e ii',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Inside bars dentro da bandeira final'),
('Bandeiras Prematuras','Padrões','Bandeiras','Armadilha','19-29','Bandeiras',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Muito cedo - não é o fim da tendência'),
('Correções como Bandeiras','Padrões','Continuação','Perspectiva','19-29','Correção',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Toda correção é bandeira potencial'),
('Triângulos - Ascendente','Padrões','Triângulos','Tipos','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Topos iguais fundos ascendentes - viés alta'),
('Triângulos - Descendente','Padrões','Triângulos','Tipos','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Fundos iguais topos descendentes - viés baixa'),
('Triângulos - Simétrico','Padrões','Triângulos','Tipos','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Ambos convergem - indefinido'),
('Triângulos - Expandido','Padrões','Triângulos','Tipos','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Expanding - volatilidade crescente'),
('Triângulos - Reversão ou Continuação','Padrões','Triângulos','Natureza','19-29','Triângulos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Ambos possíveis - aguarde breakout'),
('Triângulos - Raramente Perfeitos','Padrões','Triângulos','Natureza','19-29','Triângulos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Aceitar imperfeição nos padrões'),
('MTR - Definição','Padrões','Reversão Majoritária','Framework','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore','40-50%','Universal','Universal','Major Trend Reversal - mudança de Always In'),
('MTR - Padrão Mais Importante','Padrões','MTR','Relevância','19-29','MTR Definição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Setup principal de reversão - mais difícil'),
('MTR - Pré-Requisito 1: Quebra LT','Padrões','MTR','Pré-Requisitos','19-29','MTR Definição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Linha tendência rompida com convicção (corpo)'),
('MTR - Pré-Requisito 2: Teste do Extremo','Padrões','MTR','Pré-Requisitos','19-29','MTR Definição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Volta testar topo/fundo anterior'),
('MTR - Pré-Requisito 3: Falha Nova Extrema','Padrões','MTR','Pré-Requisitos','19-29','MTR Definição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Faz LH (topo) ou HL (fundo) - sinal entrada'),
('MTR - Pré-Requisito 4: MAG (opcional)','Padrões','MTR','Pré-Requisitos','19-29','MTR e MAG',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap da MA comum em reversões fortes'),
('MTR - LH para Topos','Padrões','MTR Tipos','Identificação','19-29','Lower High',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Lower High em topo = sinal de entrada venda'),
('MTR - HL para Fundos','Padrões','MTR Tipos','Identificação','19-29','Higher Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Higher Low em fundo = sinal de entrada compra'),
('MTR - Duplo Topo/Fundo (maioria)','Padrões','MTR Componentes','Estrutura','19-29','Duplos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Maioria dos MTR têm topo/fundo duplo'),
('MTR - Wedge Altista/Baixista','Padrões','MTR Componentes','Padrões','19-29','Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','3 pushes precedem MTR'),
('MTR - Head and Shoulders','Padrões','MTR Componentes','Padrões','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','OHO é forma de MTR'),
('MTR - Bandeira Final','Padrões','MTR Componentes','Padrões','19-29','Bandeiras Finais',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Última bandeira antes reverter'),
('MTR - Sucesso (40-50%)','Padrões','MTR','Estatística','19-29','MTR Definição',0,10,NULL,NULL,'Livro/Video/Arvore','40-50%','Universal','Universal','Inverte tendência - precisa R:R 1:2 mínimo'),
('MTR - Falha (50-60%)','Padrões','MTR','Estatística','19-29','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','50-60%','Universal','Universal','Maioria das tentativas de MTR falham'),
('MTR na Abertura','Padrões','MTR','Timing','43-46','MTR e Abertura',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Comum na primeira hora do dia'),
('MTR - Entrada Antecipada LTF','Padrões','MTR','Execução','37-42','MTR e LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrar antes de completar no CTF'),
('Reversão Minoritária - Definição','Padrões','Reversão Minoritária','Framework','19-29','MTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Minor trend reversal - correção profunda'),
('Minoritária - Vencedor 40%','Padrões','Reversão Minoritária','Estatística','19-29','Probabilidade Baixa',0,10,NULL,NULL,'Livro/Video/Arvore','40%','Universal','Universal','Baixa probabilidade - não a meta principal'),
('Reversões Comuns Mas Falham','Padrões','Reversão Minoritária','Estatística','19-29','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Maioria não resulta em reversão major'),
('Iniciantes Adoram Reversões (e perdem)','Padrões','Reversão Minoritária','Psicologia','19-29','Reversão Minoritária',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Erro mais comum - contra tendência'),
('Cunha - Definição','Padrões','Reversão - Cunha','Framework','19-29','Canal Convergente',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Wedge - 3 pushes com linhas convergentes'),
('Cunha - 3 Pushes','Padrões','Cunha','Estrutura','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Três empurrões - cada um mais fraco'),
('Como Traçar Cunha','Padrões','Cunha','Técnica','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Conectar 3 topos e fundos das correções'),
('Cunha Clássica','Padrões','Tipos Cunha','Tipos','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Padrão limpo com 3 pushes claros')
ON CONFLICT (conceito) DO UPDATE SET
  macro_categoria = EXCLUDED.macro_categoria,
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria,
  modulo_curso = EXCLUDED.modulo_curso,
  prerequisito = EXCLUDED.prerequisito,
  objetivo = EXCLUDED.objetivo,
  fonte_estudo = EXCLUDED.fonte_estudo,
  regras_operacionais = EXCLUDED.regras_operacionais,
  probabilidade = EXCLUDED.probabilidade,
  mercado_aplicavel = EXCLUDED.mercado_aplicavel,
  notas = EXCLUDED.notas;