INSERT INTO conceitos (conceito, macro_categoria, categoria, subcategoria, modulo_curso, prerequisito, conhecimento_atual, objetivo, data_estudo, tempo_investido_hrs, fonte_estudo, regras_operacionais, probabilidade, mercado_aplicavel, notas)
VALUES
('Usar Magneto Final Dia como Alvo','Habilidades Práticas','Timing','Habilidade','43-46','Magneto',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','O/H/L atrai preço'),
('Análise HTF para Contexto','Habilidades Práticas','Multi-TF','Habilidade','43-46','HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Timeframe maior = viés'),
('Identificar S/R de HTF','Habilidades Práticas','Multi-TF','Habilidade','43-46','S/R HTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Níveis mais importantes'),
('Usar LTF para Entrada Melhor','Habilidades Práticas','Multi-TF','Habilidade','43-46','LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrada prematura ou confirmação'),
('Manter Disciplina no Trade','Habilidades Práticas','Mental','Habilidade','01-07','Disciplina',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Seguir plano sem desviar'),
('Controlar FOMO','Habilidades Práticas','Mental','Habilidade','01-07','FOMO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não entrar tarde fora do plano'),
('Aceitar Perdas com Disciplina','Habilidades Práticas','Mental','Habilidade','01-07','Aceitar Incerteza',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não revenge trade'),
('Aprender com Cada Trade','Habilidades Práticas','Mental','Habilidade','01-07','Aprender com Perdas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Análise pós-trade'),
('Registrar Todos os Trades','Habilidades Práticas','Registro','Habilidade','01-07','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Trading journal completo'),
('Revisar Trades Semanalmente','Habilidades Práticas','Registro','Habilidade','01-07','Journaling',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Análise semanal de padrões'),
('Identificar Padrões de Erro','Habilidades Práticas','Registro','Habilidade','01-07','Revisão',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Erros recorrentes = prioridade de melhoria'),
('Ajustar Sistema Baseado em Feedback','Habilidades Práticas','Registro','Habilidade','01-07','Identificar Erros',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Melhoria contínua baseada em dados'),
('Fundamentos Teóricos - Domínio','Desenvolvimento','Áreas de Competência','Progresso','01-11','Fundamentos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Base teórica completa'),
('Leitura de Contexto de Mercado','Desenvolvimento','Áreas de Competência','Progresso','12-18','Contexto',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Always In / Fases / Ciclo'),
('Identificação de Estruturas','Desenvolvimento','Áreas de Competência','Progresso','12-18','Estrutura',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Tendência/Canal/TR/S/R/MM'),
('Leitura de Barras e Sinais','Desenvolvimento','Áreas de Competência','Progresso','08-11','Barras',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Qualidade/Tipo/Contexto'),
('Identificação de Padrões','Desenvolvimento','Áreas de Competência','Progresso','19-29','Padrões',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','MTR/Cunha/Duplos/Bandeiras/Clímax'),
('Análise Matemática (Prob/RR)','Desenvolvimento','Áreas de Competência','Progresso','08-11','Matemática',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Equação do trader aplicada'),
('Execução de Ordens','Desenvolvimento','Áreas de Competência','Progresso','30-36','Ordens',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Stop/Limit/Market - timing'),
('Gestão de Stop Loss','Desenvolvimento','Áreas de Competência','Progresso','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Técnico / Tamanho / Trailing'),
('Gestão de Posição','Desenvolvimento','Áreas de Competência','Progresso','30-36','Gestão',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Scale in/out / Trailing'),
('Realização de Lucros','Desenvolvimento','Áreas de Competência','Progresso','30-36','Realização',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alvos / Escalonamento'),
('Operação em Tendências','Desenvolvimento','Áreas de Competência','Progresso','37-42','Operando Tendências',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','H1/H2/BTC em contexto certo'),
('Operação em Canais','Desenvolvimento','Áreas de Competência','Progresso','37-42','Operando Canais',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Estreito/Amplo/Fade linha'),
('Operação em Trading Ranges','Desenvolvimento','Áreas de Competência','Progresso','37-42','Operando TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BLSHS/LOM/BOM'),
('Operação de Rompimentos','Desenvolvimento','Áreas de Competência','Progresso','37-42','Operando BO',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Forte/Fraco/Fade'),
('Operação de Reversões','Desenvolvimento','Áreas de Competência','Progresso','37-42','Operando MTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','MTR/Cunha/Clímax'),
('Timing (Abertura/Meio/Final)','Desenvolvimento','Áreas de Competência','Progresso','43-46','Momentos do Dia',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Características de cada período'),
('Análise Multi-Timeframe','Desenvolvimento','Áreas de Competência','Progresso','43-46','HTF/CTF/LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','HTF=viés CTF=setup LTF=entrada'),
('Psicologia e Disciplina','Desenvolvimento','Áreas de Competência','Progresso','01-07','Psicologia',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Seguir o sistema'),
('Gestão Emocional','Desenvolvimento','Áreas de Competência','Progresso','01-07','Gestão Emocional',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Controlar impulsos'),
('Journaling e Análise','Desenvolvimento','Áreas de Competência','Progresso','01-07','Registro',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Feedback loop'),
('Gestão de Perdas','Desenvolvimento','Áreas de Competência','Progresso','47-50','Gestão de Perdas',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Distinguir erros de má sorte')
ON CONFLICT (conceito) DO UPDATE SET
  macro_categoria = EXCLUDED.macro_categoria,
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria,
  modulo_curso = EXCLUDED.modulo_curso,
  prerequisito = EXCLUDED.prerequisito,
  objetivo = EXCLUDED.objetivo,
  fonte_estudo = EXCLUDED.fonte_estudo,
  regras_operacionais = EXCLUDED.regras_operacionais,
  probabilidade = EXCLUDED.probabilidade,
  mercado_aplicavel = EXCLUDED.mercado_aplicavel,
  notas = EXCLUDED.notas;