INSERT INTO conceitos (conceito, macro_categoria, categoria, subcategoria, modulo_curso, prerequisito, conhecimento_atual, objetivo, data_estudo, tempo_investido_hrs, fonte_estudo, regras_operacionais, probabilidade, mercado_aplicavel, notas)
VALUES
('Cunha Parabólica (climática)','Padrões','Tipos Cunha','Tipos','19-29','Definição Cunha e Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Push 3 climático = reversão mais forte'),
('Cunha Nested (aninhada)','Padrões','Tipos Cunha','Tipos','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Cunha dentro de cunha - exaustão múltipla'),
('Cunha Boa (em tendência fraca)','Padrões','Qualidade Cunha','Avaliação','19-29','Cunha e Tendência Fraca',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Push 3 com overshoot - provável reverter'),
('Cunha Ruim (em tendência forte)','Padrões','Qualidade Cunha','Avaliação','19-29','Cunha e Tendência Forte',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Sem sinais exaustão - continua'),
('Cunha - Overshoot','Padrões','Cunha','Variações','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Rompe linha antes de reverter - exaustão'),
('Cunha - Undershoot','Padrões','Cunha','Variações','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Não atinge linha - força diminuindo antes'),
('Cunhas Raramente Perfeitas','Padrões','Cunha','Natureza','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Aceitar imperfeição - contexto > padrão'),
('Tendências Fortes Têm Cunhas Ruins','Padrões','Cunha','Contexto','19-29','Tendência Forte',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Cunha em forte = pausa não reversão'),
('Falha de Cunha (faz Push 4)','Padrões','Cunha','Falha','19-29','Definição Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Quarta perna = não é cunha = saia da posição'),
('Cunha Altista - Entrada e Stop','Padrões','Cunha','Execução','19-29','Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,'Universal','Universal','Entrada: stop abaixo barra reversão Push3 | Stop: 1-2 ticks acima Push3 | Alvo1: início cunha | Alvo2: MM altura'),
('Cunha Baixista - Entrada e Stop','Padrões','Cunha','Execução','19-29','Cunha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,'Universal','Universal','Entrada: stop acima barra reversão Push3 | Stop: 1-2 ticks abaixo Push3 | Alvo1: início cunha | Alvo2: MM altura'),
('Double Top - Definição','Padrões','Reversão - Duplos','Framework','19-29','Swing High',0,10,NULL,NULL,'Livro/Video/Arvore','50-60%','Universal','Universal','2 topos similares - sinal venda'),
('Double Bottom - Definição','Padrões','Reversão - Duplos','Framework','19-29','Swing Low',0,10,NULL,NULL,'Livro/Video/Arvore','50-60%','Universal','Universal','2 fundos similares - sinal compra'),
('Duplos - Por Que Funcionam','Padrões','Duplos','Lógica','19-29','Definição Duplos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Trapped traders - segunda falha confirma direção'),
('Maioria Reversões São Duplos','Padrões','Duplos','Estatística','19-29','MTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Duplos são o padrão de reversão mais comum'),
('Maioria Topos São Duplos','Padrões','Duplos','Estatística','19-29','Double Top',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Natureza dos topos - sempre testar máxima'),
('Duplo Topo Perfeito (LH)','Padrões','Duplos','Qualidade','19-29','Double Top',0,10,NULL,NULL,'Livro/Video/Arvore','50-60%','Universal','Universal','T2 não chega em T1 (LH óbvio) | Entrada: stop abaixo barra reversão T2 | Stop: acima T2 | Prob 50-60%'),
('Duplo Topo Comum (igual ou excede)','Padrões','Duplos','Qualidade','19-29','Double Top',0,10,NULL,NULL,'Livro/Video/Arvore','40-50%','Universal','Universal','T2 atinge T1 - aguarde romper vale entre topos'),
('Falha de Duplo (muito comum)','Padrões','Duplos','Falha','19-29','Definição Duplos',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','T2 rompe T1 com força = era H2 - entre a favor'),
('Spring/Bear Trap (duplo fundo esp.)','Padrões','Duplos','Variação','19-29','Double Bottom',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','F2 excede F1 levemente depois retorna forte'),
('Bandeiras em Forma de Duplo','Padrões','Duplos','Contexto','19-29','Duplos e Bandeiras',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Correção como duplo topo/fundo'),
('Duplos - Movimento Projetado','Padrões','Duplos','Matemática','19-29','Duplos e MM',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Distância entre topos projetada para baixo'),
('Head and Shoulders - Definição','Padrões','Reversão - H&S','Framework','19-29','MTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Ombro-Cabeça-Ombro - forma de MTR'),
('H&S - Ombro Esquerdo','Padrões','H&S','Estrutura','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Primeiro swing da tendência'),
('H&S - Cabeça','Padrões','H&S','Estrutura','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Swing mais extremo'),
('H&S - Ombro Direito','Padrões','H&S','Estrutura','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Último swing - forma LH (topo) ou HL (fundo)'),
('H&S - Linha do Pescoço','Padrões','H&S','Estrutura','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Conecta mínimas - gatilho de entrada'),
('H&S - Resultado Majoritário (raro)','Padrões','H&S','Resultado','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Verdadeira reversão - pouco comum'),
('H&S - Resultado Minoritário (comum)','Padrões','H&S','Resultado','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Apenas correção - mais comum'),
('H&S Invertido (fundo)','Padrões','H&S','Tipos','19-29','H&S',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Inverted H&S - reversão de baixa'),
('Xícara e Alça','Padrões','Padrões Adicionais','Padrões','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Cup and handle - continuação'),
('Padrão Aninhado (Nested)','Padrões','Padrões Adicionais','Padrões','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Padrão dentro de padrão - exaustão múltipla'),
('Buying Climax - Definição','Padrões','Clímax','Framework','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Exaustão compradores - barra gigante alta'),
('Selling Climax - Definição','Padrões','Clímax','Framework','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Exaustão vendedores - barra gigante baixa'),
('Clímax - Identificação','Padrões','Clímax','Identificação','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Barra gigante (maior 50 barras) + aceleração + 3a/4a perna + distante EMA20'),
('Clímax Consecutivo','Padrões','Clímax','Padrão','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','2+ clímax seguidos - segundo geralmente falha'),
('Topos/Fundos em V','Padrões','Formato Clímax','Resultado','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Reversão abrupta após clímax'),
('Clímax - Exhaustion Gap (EG)','Padrões','Clímax Gap','Tipos','19-29','EG e Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap não preenchido = máxima/mínima do movimento'),
('Clímax - Measuring Gap (MG)','Padrões','Clímax Gap','Tipos','19-29','MG e Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Gap seguido de continuação = projeta mesmo movimento'),
('Micro Canal pode ser Clímax','Padrões','Clímax','Relação','19-29','Micro Canal',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','8+ barras sem romper = clímax disfarçado'),
('Clímax - Ação se Dentro da Posição','Padrões','Clímax','Gestão','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','3a/4a perna: realize TUDO | Se não: scale out 50-75% e move stop breakeven'),
('Clímax - Ação se Fora da Posição','Padrões','Clímax','Gestão','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','NÃO entre a favor (última barra da festa) | Aguarde TBTL | Busque H2/L2 ou MTR'),
('Falha de Consecutivo','Padrões','Clímax','Estatística','19-29','Clímax Consecutivo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Segundo clímax geralmente falha - setup venda/compra'),
('Bull Trap - Definição','Padrões','Armadilhas','Framework','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Falso rompimento de alta - compradores presos'),
('Bear Trap - Definição','Padrões','Armadilhas','Framework','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Falso rompimento de baixa - vendedores presos'),
('Armadilha Segunda Perna (comum)','Padrões','Armadilhas','Tipos','19-29','Legs',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','TBTL trap - segunda perna falsa'),
('Armadilha 5 Ticks (Emini)','Padrões','Armadilhas','Tipos','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Emini','Armadilha específica Emini - 5 ticks além pivô'),
('Armadilha 11 Pips (Forex)','Padrões','Armadilhas','Tipos','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Forex','Armadilha específica Forex - 11 pips além pivô'),
('Armadilha na Abertura','Padrões','Momento Armadilha','Timing','43-46','Abertura',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Primeira hora - 80% reversão'),
('Armadilha Final do Dia','Padrões','Momento Armadilha','Timing','43-46','Final Dia',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Última hora - breakouts falhos'),
('Armadilha Após Clímax','Padrões','Momento Armadilha','Timing','19-29','Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Pós-exaustão - setup mais confiável'),
('Armadilha Em TR','Padrões','Momento Armadilha','Timing','12-18','TR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Falsos BOs nas extremidades do range'),
('Armadilha e Exaustão','Padrões','Armadilhas','Relação','19-29','Armadilha e Clímax',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Trap = sinal de exaustão iminente'),
('Falha de Armadilha (vira tendência)','Padrões','Armadilhas','Falha','19-29','Armadilha',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BO real após trap falhado - raro mas poderoso'),
('Topos/Fundos Arredondados','Padrões','Outros Padrões','Padrões','19-29','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Geralmente é cunha disfarçada'),
('Breakout Bem Sucedido (Strong BO)','Padrões','Rompimento','Setup Específico','12-18','BO Forte',0,10,NULL,NULL,'Livro/Video/Arvore','60-70%','Universal','Universal','Entrada: Market/BTC/Stop High+1 | Stop: Swing anterior ou 2x barra | Alvo: MM ou próximo S/R HTF'),
('Breakout Fraco/Falhado','Padrões','Rompimento','Setup Específico','12-18','BO Fraco',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','Fade: aguarde retornar ao range | Entrada: stop contra BO | Stop: além extremo BO | Alvo: meio range'),
('Vacuum Effect (Efeito Vácuo)','Padrões','Rompimento','Setup Específico','12-18','Efeito Vácuo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,'Universal','Universal','NÃO entre durante vácuo | Aguarde teste S/R | Reversão no teste com pavio longo | Alvo: origem do vácuo'),
('Failed Breakout Fade Setup','Padrões','TR','Setup Específico','12-18','Regra dos 80%',0,10,NULL,NULL,'Livro/Video/Arvore','80%','Universal','Universal','BO retornou dentro: stop abaixo/acima retorno | Stop: 1-2 ticks além pico BO | Alvo1: meio range | Alvo2: fundo/topo range'),
('Swing Trading','Decisão e Operação','Tipos de Operação','Estilo','30-36','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Retorno 2x+ risco | Ambiente: tendência e canal | Operação base do iniciante'),
('Scalping','Decisão e Operação','Tipos de Operação','Estilo','30-36','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Retorno <2x risco | Múltiplas operações | NÃO para iniciantes'),
('Scalp - Tamanho Mínimo Emini','Decisão e Operação','Scalping','Parâmetros','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Emini','4 ticks mínimo no Emini para cobrir custos'),
('Scalp - Dois Timeframes','Decisão e Operação','Scalping','Técnica','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Opera no gráfico de 2min com referência 5min'),
('Scalp - Gráfico 2 Minutos','Decisão e Operação','Scalping','Ferramentas','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Timeframe principal para scalp'),
('Scalp - Gráfico 15 Segundos','Decisão e Operação','Scalping','Ferramentas','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrada muito precisa - avançado'),
('Scalp - 50 Setups/Dia','Decisão e Operação','Scalping','Quantidade','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Volume alto de setups - requer velocidade'),
('Scalp em TR','Decisão e Operação','Scalping','Ambiente','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Melhor ambiente para scalp'),
('Scalp em BO Forte','Decisão e Operação','Scalping','Ambiente','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','BO forte também permite scalp'),
('Perda se Gerenciar Scalp Como Swing','Decisão e Operação','Scalping','Erro Fatal','30-36','Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Alvos muito grandes para scalp = perde'),
('Convertendo Swing para Scalp','Decisão e Operação','Tipos de Operação','Adaptação','30-36','Swing Trading e Scalping',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Quando trade não desenvolve - aceite lucro menor'),
('Stop Order','Decisão e Operação','Ordens','Tipos','30-36','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra ACIMA / Venda ABAIXO | Para rompimentos | Melhores para maioria'),
('Limit Order','Decisão e Operação','Ordens','Tipos','30-36','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra ABAIXO / Venda ACIMA | Para pullbacks e fade | Traders habilidosos'),
('Market Order','Decisão e Operação','Ordens','Tipos','30-36','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Imediata a qualquer preço | Urgência máxima | Use raramente'),
('Bracket Order','Decisão e Operação','Ordens','Tipos','30-36','Stop Order e Limit Order',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrada + stop + alvo em ordem única'),
('Scale In com Limit Orders','Decisão e Operação','Ordens','Técnica','30-36','Limit Order',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Múltiplas limits em diferentes níveis - LOM'),
('Stop Order para Iniciantes','Decisão e Operação','Ordens','Recomendação','30-36','Stop Order',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mais segura - confirma direção antes entrar'),
('Ordens na Abertura (Stop Melhores)','Decisão e Operação','Ordens','Timing','43-46','Stop Order',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Abertura: stop orders mais seguras'),
('Limite para LOM Estabelecido','Decisão e Operação','Ordens','Contexto','30-36','LOM',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Use limit apenas em TR estabelecida'),
('Timing de Entrada - Antecipado','Decisão e Operação','Entrada','Timing','30-36','Entrada',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Antes completar setup | Melhor preço | Mais risco'),
('Timing de Entrada - Na Hora','Decisão e Operação','Entrada','Timing','30-36','Entrada',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','No sinal | Balance de preço e confirmação'),
('Timing de Entrada - Atrasado','Decisão e Operação','Entrada','Timing','30-36','Entrada',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Após confirmação | Pior preço | Menos risco'),
('Entrada Prematura via LTF','Decisão e Operação','Entrada','Técnica Avançada','30-36','LTF',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Entrar no LTF antes do sinal no CTF'),
('Como Entrar em Reversões','Decisão e Operação','Entrada','Contexto','30-36','MTR',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Aguardar LH/HL confirmado antes entrar'),
('Tamanho de Posição','Decisão e Operação','Entrada','Sizing','30-36','Risco',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Calcular contratos baseado no risco fixo'),
('Posição Total vs Fracionada','Decisão e Operação','Entrada','Sizing','30-36','Tamanho Posição',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','1 entrada total vs múltiplas entradas menores'),
('BTC - Buy The Close','Decisão e Operação','Entrada','Técnica Específica','30-36','Tendência Alta',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Comprar no fechamento de cada barra que fecha forte | Canal estreito | Vantagem: confirmação máxima | Desvantagem: pior preço'),
('STC - Sell The Close','Decisão e Operação','Entrada','Técnica Específica','30-36','Tendência Baixa',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Vender no fechamento de cada barra que fecha fraca | Canal estreito baixa | Invertido do BTC'),
('Price Action Stop (Stop Técnico)','Decisão e Operação','Stop Loss','Tipos','30-36','Nenhum',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Compra: abaixo último HL major | Venda: acima último LH major | Onde premissa é invalidada'),
('Catastrophe Stop','Decisão e Operação','Stop Loss','Tipos','30-36','MM',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Para breakouts: MM barra/padrão projetado direção oposta | Ex: BO 20pts = stop 20pts abaixo topo'),
('Stop Breakeven','Decisão e Operação','Stop Loss','Tipos','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Mover stop para entrada após trade confirmar'),
('Trailing Stop','Decisão e Operação','Stop Loss','Tipos','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Seguir abaixo cada novo HL (alta) ou acima LH (baixa)'),
('Stop Fixo','Decisão e Operação','Stop Loss','Tipos','30-36','Risco Fixo',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Valor fixo por trade - menos técnico'),
('Stop Apertado (scalp/tendência forte)','Decisão e Operação','Stop Loss','Tamanho','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Abaixo barra sinal apenas - correções rasas'),
('Stop Médio','Decisão e Operação','Stop Loss','Tamanho','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Beyond swing minor - padrão'),
('Stop Largo (TR/contra tendência)','Decisão e Operação','Stop Loss','Tamanho','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Beyond swing major - canal amplo e TR'),
('Stop Correto (não arbitrário)','Decisão e Operação','Stop Loss','Princípio','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Escolha stop técnico PRIMEIRO depois calcule tamanho'),
('Stop Determina Tamanho Posição','Decisão e Operação','Stop Loss','Princípio','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Risco fixo / distância stop = nº contratos'),
('Regra: Nunca Mover Stop Contra','Decisão e Operação','Stop Loss','Regra','30-36','Trailing Stop',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','NUNCA ampliar risco - só mover a favor'),
('Saia se Premissa Mudar','Decisão e Operação','Stop Loss','Regra','30-36','Stop Loss',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Razão da entrada não existe mais = saia imediatamente'),
('Stop Compradores: Abaixo HL','Decisão e Operação','Stop Loss','Regra','30-36','Higher Low',0,10,NULL,NULL,'Livro/Video/Arvore',NULL,NULL,'Universal','Para compras: stop abaixo último HL major')
ON CONFLICT (conceito) DO UPDATE SET
  macro_categoria = EXCLUDED.macro_categoria,
  categoria = EXCLUDED.categoria,
  subcategoria = EXCLUDED.subcategoria,
  modulo_curso = EXCLUDED.modulo_curso,
  prerequisito = EXCLUDED.prerequisito,
  objetivo = EXCLUDED.objetivo,
  fonte_estudo = EXCLUDED.fonte_estudo,
  regras_operacionais = EXCLUDED.regras_operacionais,
  probabilidade = EXCLUDED.probabilidade,
  mercado_aplicavel = EXCLUDED.mercado_aplicavel,
  notas = EXCLUDED.notas;